### PR TITLE
Initial french translation

### PR DESCRIPTION
**Pull request by frerepoulet**
Initial french translation

### CODE REVIEW

**Comment by frerepoulet** [comment]
It seems there is a problem with the fonts for the french version on safari.  The accents don't show (but replaced by alternative font) and the font isn't the same as the original version.  The Hungarian version seems fine.  I'm on macOS if it could help...

French version on Safari : 
frenchSafari

Hungarian version on Safari:
hungarianSafari

French version on Chrome:
frenchChrome

**Comment by HelloZeroNet** [comment]
Yeah, Roboto missing some accents. On windows I added 'Segoe UI' as fallback (windows system font with similar line width). If we could find a similar replacement font for macOS, then I can also add that one

**Comment by HelloZeroNet** [comment]
Looks like Safari does not fallback for missing characters (`'Roboto', 'Helvetica Neue'` does not work), so I moved Helvetica neue to the front: `'Helvetica Neue', 'Roboto', 'Segoe UI', 'Helvetica'`

**Comment by frerepoulet** [comment]
Solved then. Thanks 👍

**Pull request merged**
